language: go

go:
  - 1.10

install:
  - go get golang.org/x/lint/golint
  - go get github.com/chromium/hstspreload
  - go get cloud.google.com/go/datastore
  - go get google.golang.org/api/option
  - go get google.golang.org/appengine
  - go get google.golang.org/grpc
  - make get-datastore-emulator

script:
  - make travis
